### PR TITLE
Build and Deploy OCI Image of ps-printer-app Using Rockcraft

### PR DESCRIPTION
**Pull request by rudra-iitm**
This PR introduces the necessary code and configurations to build and deploy the OCI image of `ps-printer-app` using [**Rockcraft**](https://github.com/canonical/rockcraft). Below are the key highlights and updates:

### Key Changes
- **Rockcraft Configuration**:  
  Added a `rock/rockcraft.yaml` file containing all the configurations required to build the rock for `ps-printer-app`.

- **GitHub Workflows**:  
  Introduced workflows to build and publish Docker images and GitHub packages.  
  **Note**: Publishing to Docker Hub is currently commented out until OpenPrinting's Docker Hub setup is finalized.

- **Auto-Update Enhancements**:  
  Updated the `auto-update.yml` workflow to include the latest changes ubuntu/desktop-snaps/pull/813 from the `desktop/snap` repository.  
  This update enables support for specifying a path to the YAML file that needs to be updated.

### CODE REVIEW

**Comment by rudra-iitm** [comment]
@tillkamppeter Pls review this PR

**Comment by tillkamppeter** [comment]
On a first glance, I already found a big problem: The `rock/` subdirectory seems to contain a full copy of the whole project. These are either duplicate files or the original files with small, rock-specific modifications. In any case, this is a maintenance nightmare. The principal code and its build system and documentation files should be there only once, in the main directory, and serve for all packaging/installation methods: Classic, Snap, and Rock. If there are differences needed, this should be done with macros controlled by the `./configure` command line and with conditional compiling in the code (`#ifdef ...`).

In a free software source repository there should be NEVER duplicate files or files which differ only slightly.

On does not easily see what the differences are and how to apply changes and fixes then and one also easily forgets to apply a fix to all incarnations of the file.

Could you change that?

**Comment by rudra-iitm** [comment]
While building and packing, Rockcraft works in its own LXD container and checks out only the directory where 'rockcraft.yaml' is present.

To avoid duplicate files, we can place both 'rockcraft.yaml' and 'snapcraft.yaml' in the root directory along with all other shared files.

To implement this, I need to make a few additional modifications to the 'ubuntu/desktop-snap' repository, which need to be approved by Sergio Costas, sir.

**Comment by tillkamppeter** [comment]
@rudra-iitm yes, please do it this way.

**Comment by rudra-iitm** [comment]
@tillkamppeter, can you pls review this again

**Pull request merged**
